hostinfo:
  - host: znet-jon
    ip: 192.168.1.150
    name: znet-jon
    connection: Ethernet
  - host: znet-danae
    ip: 192.168.1.151
    name: znet-danae
    connection: Ethernet
  - host: znet-malikai
    ip: 192.168.1.152
    name: znet-malikai
    connection: Ethernet
  - host: zpi-workstation
    ip: 192.168.1.130
    name: zpi-workstation
    connection: wlan0
